### ISSUE TITLE
Cannot install kernel-cachyos

### ISSUE THREAD

**Issue by Chevek** [CosmicFusion/fedora-kernel-manager#3]
When trying to install cachyos kernel, I got an error :
"Error: Unable to find a match: kernel-cachyos kernel-cachyos-devel-matched"

I used the latest binary one can find in Actions here.

See this screenshot for more details:
![Capture d’écran du 2024-07-18 00-07-04](https://github.com/user-attachments/assets/ecf48d7d-cb17-4a49-ac31-669fcc024234)

Regards

**Comment by CosmicFusion** [comment]
can you check if you have the cachyos copr enabled?

**Comment by CosmicFusion** [comment]
The Cachyos repo was moved and such, you need to get a new cachyos-config from their copr

**Comment by Chevek** [comment]
Hi,

I tried to build from sources, but I've an error when launching on Fedora 41:
```
$ cargo run
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.07s
warning: the following packages contain code that will be rejected by a future version of Rust: bindgen v0.51.1, cexpr v0.3.6, nom v4.2.3
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
     Running `target/debug/fedora-kernel-manager`
thread 'main' panicked at src/main.rs:22:82:
No translation files found: Os { code: 2, kind: NotFound, message: "Aucun fichier ou dossier de ce nom" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x560d3e78edea - std::backtrace_rs::backtrace::libunwind::trace::hc95d5865fac762ab
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/std/src/../../backtrace/src/backtrace/libunwind.rs:116:5
   1:     0x560d3e78edea - std::backtrace_rs::backtrace::trace_unsynchronized::h4c4e19dc37d4a259
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x560d3e78edea - std::sys::backtrace::_print_fmt::h8b67ce6ab416ad9e
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/std/src/sys/backtrace.rs:66:9
   3:     0x560d3e78edea - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::he54e0d7cddc74726
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/std/src/sys/backtrace.rs:39:26
   4:     0x560d3e7b76ab - core::fmt::rt::Argument::fmt::h3b1e02bac1f59872
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/core/src/fmt/rt.rs:177:76
   5:     0x560d3e7b76ab - core::fmt::write::h423a491e580487d8
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/core/src/fmt/mod.rs:1178:21
   6:     0x560d3e78b483 - std::io::Write::write_fmt::h1d3835ba798f3798
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/std/src/io/mod.rs:1823:15
   7:     0x560d3e790132 - std::sys::backtrace::BacktraceLock::print::hb23090d1daebc95a
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/std/src/sys/backtrace.rs:42:9
   8:     0x560d3e790132 - std::panicking::default_hook::{{closure}}::h7cc99a4ce5e217a1
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/std/src/panicking.rs:266:22
   9:     0x560d3e78fd9e - std::panicking::default_hook::h507cf3b38a81a3d0
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/std/src/panicking.rs:293:9
  10:     0x560d3e7909bf - std::panicking::rust_panic_with_hook::h1de8ee9c2f588d0a
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/std/src/panicking.rs:797:13
  11:     0x560d3e790673 - std::panicking::begin_panic_handler::{{closure}}::h21b12e4fa56a76a5
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/std/src/panicking.rs:664:13
  12:     0x560d3e78f2c9 - std::sys::backtrace::__rust_end_short_backtrace::h0adeef81e27aa4a5
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/std/src/sys/backtrace.rs:170:18
  13:     0x560d3e790334 - rust_begin_unwind
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/std/src/panicking.rs:662:5
  14:     0x560d3e1e7f85 - core::panicking::panic_nounwind_fmt::runtime::hb6742d58e107eaa4
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/core/src/panicking.rs:112:18
  15:     0x560d3e1e7f85 - core::panicking::panic_nounwind_fmt::ha98c557803baabac
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/core/src/panicking.rs:122:5
  16:     0x560d3e1e8012 - core::panicking::panic_nounwind::h55bd0c436376ffda
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/core/src/panicking.rs:221:5
  17:     0x560d3e1e81d6 - core::panicking::panic_cannot_unwind::hf3a7fc3dbecd5e37
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/core/src/panicking.rs:310:5
  18:     0x560d3e1f09bd - gio::auto::application::ApplicationExt::connect_activate::activate_trampoline::hb511056bf9345077
                               at /home/yannick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gio-0.19.5/src/auto/application.rs:453:9
  19:     0x7fe982d287da - g_closure_invoke
  20:     0x7fe982d588f3 - <unknown>
  21:     0x7fe982d493e9 - <unknown>
  22:     0x7fe982d49671 - g_signal_emit_valist
  23:     0x7fe982d49733 - g_signal_emit
  24:     0x7fe9819a9b40 - <unknown>
  25:     0x7fe9819a9ce3 - g_application_run
  26:     0x560d3e23f262 - gio::application::ApplicationExtManual::run_with_args::hfa6dd5b5a76bd4ec
                               at /home/yannick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gio-0.19.5/src/application.rs:29:13
  27:     0x560d3e23f349 - gio::application::ApplicationExtManual::run::h62338a951f6a8223
                               at /home/yannick/.cargo/registry/src/index.crates.io-6f17d22bba15001f/gio-0.19.5/src/application.rs:22:9
  28:     0x560d3e26f721 - fedora_kernel_manager::main::h2895cbc10ce52460
                               at /home/yannick/Téléchargements/fedora-kernel-manager-0.1.4/src/main.rs:99:5
  29:     0x560d3e2553fb - core::ops::function::FnOnce::call_once::h09ee60a4a87845de
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/core/src/ops/function.rs:250:5
  30:     0x560d3e27475e - std::sys::backtrace::__rust_begin_short_backtrace::h1ce28e5f143372ad
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/std/src/sys/backtrace.rs:154:18
  31:     0x560d3e2758f1 - std::rt::lang_start::{{closure}}::h05bb9f247e6c371e
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/std/src/rt.rs:164:18
  32:     0x560d3e786440 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h3d4aab4f1f8691f9
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/core/src/ops/function.rs:284:13
  33:     0x560d3e786440 - std::panicking::try::do_call::h53ce73a313d4ef92
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/std/src/panicking.rs:554:40
  34:     0x560d3e786440 - std::panicking::try::hdcfb42c82b725b1e
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/std/src/panicking.rs:518:19
  35:     0x560d3e786440 - std::panic::catch_unwind::h8bee56582502184d
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/std/src/panic.rs:345:14
  36:     0x560d3e786440 - std::rt::lang_start_internal::{{closure}}::h741ca67a5423136f
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/std/src/rt.rs:143:48
  37:     0x560d3e786440 - std::panicking::try::do_call::hdd5f7fdb6b9993bc
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/std/src/panicking.rs:554:40
  38:     0x560d3e786440 - std::panicking::try::heda5b652e5fa53d7
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/std/src/panicking.rs:518:19
  39:     0x560d3e786440 - std::panic::catch_unwind::h5fc74880b939df05
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/std/src/panic.rs:345:14
  40:     0x560d3e786440 - std::rt::lang_start_internal::h2ad17c1fc703a6c6
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/std/src/rt.rs:143:20
  41:     0x560d3e2758ca - std::rt::lang_start::h534d159e1552236f
                               at /builddir/build/BUILD/rust-1.82.0-build/rustc-1.82.0-src/library/std/src/rt.rs:163:17
  42:     0x560d3e27006e - main
  43:     0x7fe9814a6248 - __libc_start_call_main
  44:     0x7fe9814a630b - __libc_start_main@GLIBC_2.2.5
  45:     0x560d3e1e8a95 - _start
  46:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.
Abandon (core dumped)
```

**Comment by CosmicFusion** [comment]
You can’t use cargo run, do sudo make install

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Chevek** [comment]
Thank you !! That works, now I've to try it more. Kind regards.
